version: '3'

services:
    bot:
        image: darrenofficial/dmusicbot:v4
        # restart: unless-stopped
        env_file: .env
        networks:
            - lavalink-net
        depends_on:
            - lavalink
        volumes:
            - ./botconfig.js:/usr/src/app/botconfig.js:ro

    lavalink:
        image: fredboat/lavalink:dev
        hostname: lavalink
        restart: unless-stopped
        networks:
            - lavalink-net
        volumes:
            - ./docker/application.yml:/opt/Lavalink/application.yml:ro

networks:
    lavalink-net:
